on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repository
       uses: actions/checkout@master
     - name: Build the Docker image
       run: docker build . --file Dockerfile
     - name: Upload rendered paper
       uses: actions/upload-artifact@v4
       with:
         name: rendered-paper
         path: analysis/paper/paper.html
